---
title: "ACLU Child Separations"
output: html_notebook
---

```{r message=FALSE, warning=FALSE, error=TRUE}
# load libraries
library(dplyr)
library(readr)

```

```{r error=TRUE}
# load data
aclu <- read_csv('aclu_separations.csv')

```

```{r error=TRUE}
# inspect data
head(aclu)
summary(aclu)

```

```{r error=TRUE}
# select columns
aclu <- aclu %>%
select(-addr)


```

```{r error=TRUE}
# view columns
print(colnames(aclu))
```

```{r error=TRUE}
# rename columns
aclu <- aclu %>%
  rename(city = program_city, state = program_state, number_children = n, longitude = lon, latitude = lat)

print(colnames(aclu))
```

```{r error=TRUE}
# add column
border_latitude = 25.83

aclu <- aclu %>%
  mutate(last_change_border = latitude - border_latitude)
```

```{r error=TRUE}
# latitude change

further_away <- aclu%>%
  filter(last_change_border > 15) %>%
  arrange(desc(last_change_border))
head(further_away)

```

```{r error=TRUE}
# number of children
ordered_by_children <- aclu%>%
  arrange(desc(number_children))
head(ordered_by_children)

```

```{r error=TRUE}
# state analysis
chosen_state <- "AK"

chosen_state_separations <- aclu %>%
  filter(state == chosen_state) %>%
  arrange(desc(number_children))
    
head(chosen_state_separations)

```
