---
title: "Aggregates in R"
output: html_notebook
---

```{r message = FALSE}
# load packages
library(readr)
library(dplyr)
```

```{r message = FALSE}
# load orders data
orders <- read_csv("orders.csv")

# inspect orders
head(orders)
```

```{r}
# define pricey_shoes here:
pricey_shoes <- orders %>%
  group_by(shoe_type) %>%
    summarize(max_price = max(price, na.rm = TRUE))
pricey_shoes


```

```{r}
# define shoes_sold here:
shoes_sold <- orders %>%
group_by(shoe_type) %>%
summarize(count = n())

shoes_sold


```

---
title: "Aggregates in R"
output: html_notebook
---

```{r message = FALSE}
# load packages
library(readr)
library(dplyr)
```

```{r message = FALSE}
# load orders data
orders <- read_csv("orders.csv")

# inspect orders
head(orders)
```

```{r}
# define shoe_counts here:
shoe_counts <- orders %>%
  group_by(shoe_type,shoe_color) %>%
  summarize(count = n())

shoe_counts



```

```{r}
# define shoe_prices here:

shoe_prices <- orders %>%
  group_by(shoe_type,shoe_material) %>%
    summarize(mean_price = mean(price, na.rm = TRUE))

shoe_prices

```
