#Dealing with Multiple Files

---
title: "Data Cleaning in R"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
# load libraries
library(readr)
library(dplyr)
```

```{r}
# list files
student_files <- list.files(pattern = "exams_.*csv")

```

```{r message=FALSE}
# read files
df_list <- lapply(student_files, read_csv)
```

```{r}
# concatenate data frames
students <- bind_rows(df_list)

```

```{r}
# number of rows in students
nrow_students<-nrow(students)

```


#Reshaping your Data

---
title: "Data Cleaning in R"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
# load libraries
library(dplyr)
library(tidyr)
```

```{r}
# load students data frame
load("students.Rda")
```

```{r}
# original column names
original_col_names <- colnames(students)
print(original_col_names)

```

```{r}
# gather columns
students <- students%>%
  gather('fractions', 'probability',key='exam',value='score')
head(students)


```

```{r}
# updated column names
gathered_col_names<- colnames(students)
print(gathered_col_names)

```

```{r}
# unique value counts of exam
exam_counts <- students%>%
  count(exam)
print(exam_counts)


```

